### ISSUE TITLE
doc says that puppetlabs/apt can manage unattended-upgrades config but I can't find it

### ISSUE THREAD

**Issue by Fr33maan** [andschwa/puppet-unattended_upgrades#13]
Hi, I've posted the question [on SO](http://stackoverflow.com/questions/44058535/puppetlabs-apt-and-unattended-upgrades) because your doc says that puppetlabs/apt can manage unattended-upgrades config.

I cannot find how to do that in puppetlabs/apt doc, could you confirm that it is correct or maybe share your config ?

Thanks

**Comment by andyleejordan** [comment]
It looks like it got [removed](https://github.com/puppetlabs/puppetlabs-apt/blob/03681047ed16a1f88d63fe1cd07ea85815257b6f/CHANGELOG.md#L196) and is now part of [this module](https://github.com/voxpupuli/puppet-unattended_upgrades).
