### ISSUE TITLE
Module do not compatible with Ubuntu

### ISSUE THREAD

**Issue by DmitryINdig0** [andschwa/puppet-unattended_upgrades#3]
Hello,

Seems it is not work with Ubuntu because of in Debian used "Unattended-Upgrade::Origins-Pattern" rather in the Ubuntu used "Unattended-Upgrade::Allowed-Origins".
Checked on Ubuntu 14.04.2 LTS

**Comment by DmitryINdig0** [comment]
Looks like module should determinate which directive it should apply dependency from OS distributive, but in my case on Ubuntu had been used  "Unattended-Upgrade::Origins-Pattern". I'll try figure out why...

**Comment by andyleejordan** [comment]
Feel free to PR a fix.
